oakd:
 ros__parameters:
  camera:
   i_enable_imu: false
   i_enable_ir: false
   i_floodlight_brightness: 0
   i_laser_dot_brightness: 100
   i_nn_type: none
   i_pipeline_type: RGBD
   i_usb_speed: SUPER_PLUS
  rgb:
   i_board_socket_id: 0
   i_fps: 10.0
   i_interleaved: false
   i_max_q_size: 10
   i_preview_size: 360
   i_enable_preview: true
   i_low_bandwidth: true
   i_keep_preview_aspect_ratio: true
   i_publish_topic: false
   i_resolution: '720p'
  stereo:
   i_publish_topic: true
   i_align_depth: true
   i_height: 360
   i_width: 640
   i_subpixel: true
   i_left_right_check: true
   i_depth_filter_size: 7
   i_stero_confidence_threshold: 200

  use_sim_time: false
